name: CD Pipeline

on:
  push:
    branches:
      - main  # Run the workflow when changes are pushed to main

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Pulls the repository code

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Specify the Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build and push Docker image
        run: |
          docker build -t your-dockerhub-username/fastapi-app:latest .
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
          docker push your-dockerhub-username/fastapi-app:latest

      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker pull your-dockerhub-username/fastapi-app:latest
            docker stop fastapi-container || true
            docker rm fastapi-container || true
            docker run -d --name fastapi-container -p 8000:8000 your-dockerhub-username/fastapi-app:latest